// Run against an isolated, unstarted backend; never use a production instance.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir, writeFile} from 'node:fs/promises';
const require = createRequire(process.env.PLAYWRIGHT_PACKAGE || '/Users/cactusxiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium} = require('playwright');
const base = process.env.ORBBEC_YAML_TEST_URL;
const description = process.env.YAML_DESCRIPTION_PATH;
const demo = process.env.DEMO_VIDEO_PATH;
assert(base && description && demo, 'Set isolated backend URL, YAML_DESCRIPTION_PATH and DEMO_VIDEO_PATH');
const output = process.env.TEST_OUTPUT || '/tmp/orbbec-yaml-ui';
await mkdir(output, {recursive: true});
const browser = await chromium.launch({executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true});
const page = await browser.newPage({viewport: {width: 1280, height: 1000}});
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const check = message => {checks.push(message); console.log('PASS', message)};
try {
  const setup = await page.request.post(base + '/setup/empty', {form: {instance_label: 'yaml-browser'}});
  assert(setup.ok(), await setup.text());
  await page.goto(base + '/manage/tasks/new');
  await page.locator('#task-json').setInputFiles({name: 'bad.yaml', mimeType: 'application/yaml', buffer: Buffer.from('task: [bad')});
  await page.getByText('任务描述 YAML 格式无效，请检查缩进和引号', {exact: true}).waitFor();
  assert(await page.locator('#confirm').isDisabled());
  check('invalid YAML blocks upload with readable error');
  await page.locator('#total').fill('3');
  await page.locator('#task-json').setInputFiles(description);
  await page.waitForFunction(() => document.querySelector('#task-name').value === 'place_the_cube_into_the_box');
  assert.equal(await page.locator('#total').inputValue(), '3');
  assert.match(await page.locator('#preview').innerText(), /将魔方放入纸盒中/);
  assert.match(await page.locator('#preview').innerText(), /Place the cube into the box/);
  check('original extensionless NAS description fills task name and bilingual steps; keeps selected total');
  await page.locator('#total').fill('1.5');
  assert.equal(await page.locator('#total').evaluate(input => input.validity.valid), false);
  await page.locator('#total').fill('0');
  assert.equal(await page.locator('#total').evaluate(input => input.validity.valid), false);
  await page.locator('#total').fill('3');
  await page.locator('#demo-video').setInputFiles(demo);
  await page.screenshot({path: output + '/yaml-task-form.png', fullPage: true});
  await page.locator('#confirm').click();
  await page.waitForURL(base + '/tasks/place_the_cube_into_the_box');
  assert.match(await page.locator('.metric').first().innerText(), /\b3\b/);
  await page.locator('video').evaluate(v => {v.muted = true; return v.play()});
  await page.waitForFunction(() => document.querySelector('video').currentTime > 0);
  check('YAML and video uploaded; task requires 3 episodes and demo plays');
  const registered = await page.request.post(base + '/api/v1/auth/register', {data: {username: 'yaml.browser', password: 'yaml-test-password', password_repeat: 'yaml-test-password'}});
  assert(registered.ok(), await registered.text());
  await page.goto(base + '/operator');
  await page.locator('#name').fill('yaml.browser');
  await page.locator('#password').fill('yaml-test-password');
  await page.locator('#loginButton').click();
  await page.waitForFunction(() => document.querySelector('#progress').textContent === '0 / 3');
  assert.match(await page.locator('#description').innerText(), /将魔方放入纸盒中/);
  await page.setViewportSize({width: 390, height: 844});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({path: output + '/yaml-operator-mobile.png', fullPage: true});
  check('operator sees YAML steps and 0 / 3 progress on mobile layout');
  assert.deepEqual(errors, []);
} finally {
  await writeFile(output + '/browser-results.json', JSON.stringify({checks, errors}, null, 2));
  await browser.close();
}
